spring:
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/social_media_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
